services:
  events-db:
    image: postgres:latest
    container_name: events-db
    environment:
      POSTGRES_USER: esii
      POSTGRES_PASSWORD: esii
      POSTGRES_DB: events
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  events-api:
    container_name: events-api
    image: events-api:latest
    ports:
      - 8080:8080
    environment:
      - DB_HOST=events-db
      - DB_PORT=5432
      - DB_NAME=events
      - DB_USER=esii
      - DB_PASSWORD=esii
      - MAIL_SENDER_HOST=smtp.gmail.com
      - MAIL_SENDER_PORT=587
      - MAIL_SENDER_USER=egsoft502@gmail.com
      - MAIL_SENDER_PASSWORD=vzjr nnab ffwq rput
      - spring_profiles_active=prod
    depends_on:
      - events-db

  eventos-web: 
    container_name: eventos-web
    image: eventos-web:latest
    ports:
      - 80:80
    environment:
      - EVENTOS_API_URL=http://events-api:8080
    depends_on:
      - events-api

volumes:
  postgres_data:
